[package]
name = "nanocron"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
cron = "0.9.0"
seahorse = "1.1.2"
shell-words = "1.0.0"
